import Scene, OverLoad

Scene.StoryOverView.create_time_axis('８巻')
Scene.StoryOverView.create_new_scene('これまで')
ains = OverLoad.Character("アインズ・ウール・ゴウン", 200, 100, None, None, None)
enri = OverLoad.Character("エンリ・エモット", 16, 2, {"ファーマー": 1, "サージェント": 1})
nem = OverLoad.Character("ネム・エモット", 10, 1)
nphylea = OverLoad.Character("ンフィーレア・バレアレ", 16, 12,{"ウィザード": 3, "アルケミスト": 4, "ファーマシスト": 4,
                                                    "ドクター": 1}, "あらゆる装備をペナルティなしで装備できる")
Scene.StoryOverView.grant_relation_one_side(enri, '村の救世主', ains)
Scene.StoryOverView.grant_relation_one_side(nphylea, '強大な力の持ち主', ains)
Scene.StoryOverView.grant_relation_one_side(ains, 'タレント持ちで有用', nphylea)
Scene.StoryOverView.grant_relation_one_side(enri, '友達', nphylea)
Scene.StoryOverView.grant_relation_one_side(nphylea, '片想い', enri)
Scene.StoryOverView.grant_relation_one_side(enri, '妹', nem)
Scene.StoryOverView.grant_relation_one_side(nem, '姉', enri)

Scene.StoryOverView.create_next_scene('森に向かう')
enri.change_item("薬草",200)
nphylea.relate_scene()
Scene.StoryOverView.create_next_scene('ホブゴブリンとの出会い')
hobgoblin = OverLoad.Character("ホブゴブリン", 5, 2, None, None, None)
enri.relate_scene()
nphylea.relate_scene()
Scene.StoryOverView.create_next_scene('エランテルへ（エンリ）')
enri.change_item("薬草",0)
enri.change_item("お金",50000)
Scene.StoryOverView.create_next_scene('トロール襲撃')
enri.change_level(6)
enri.change_class_level({"コマンダー": 2, "ジェネラル": 2})
Scene.StoryOverView.grant_relation_each_other(nphylea, '恋人', enri)
Scene.StoryOverView.create_next_scene('ナザリックへの訪問')
enri.relate_scene()
nphylea.relate_scene()
nem.relate_scene()
ains.relate_scene()

Scene.StoryOverView.set_scene('ナザリックへの訪問')

Scene.StoryOverView.show_dict(Scene.StoryOverView.current_value(enri))
Scene.StoryOverView.show_dict(Scene.StoryOverView.current_relation(enri))
Scene.StoryOverView.show_dict(Scene.StoryOverView.that_time_relation(enri,'これまで'))

Scene.StoryOverView.set_scene('エランテルへ（エンリ）')
Scene.StoryOverView.create_same_time_scene('エランテルへ（モモン）')
Scene.StoryOverView.create_next_scene('ルプスへの説教')
Scene.StoryOverView.create_next_scene('グの退治')
Scene.StoryOverView.create_next_scene('空の場面（トロール襲撃と同じ時間）')
Scene.StoryOverView.grant_same_time_context('トロール襲撃', '空の場面（トロール襲撃と同じ時間）')
